export const CLIENT_PATHS = {
  user: '/user',
  cart: '/cart',
  movies: '/movies',
  signin: '/signin',
  signup: '/signup',
  adminMovies: '/admin/movies',
  notFound: '/notFound',
  admin: '/admin',
  main: '/',
  comments: '/comments',
  userChat: '/userChat',
};

export const SERVER_PATHS = {
  signin: '/signin',
  signup: '/signup',
  logout: '/signout',
  cart: '/cart',
  users: '/users',
  movies: '/films',
  actors: '/actors',
  genres: '/genres',
  categories: '/categories',
  favorites: '/favorites',
  admin: '/admin',
  profile: '/profile',
  orders: '/orders',
  myMovies: '/orders/myfilms',
  main: '/',
  commentaries: '/commentaries',
};
