/* eslint-disable no-shadow */

export enum MoviesActionTypes {
  GET_MOVIES_BY_QUERY = 'GET_MOVIES_BY_QUERY',
  ADD_FILTER_OPTION = 'ADD_FILTER_OPTION',
  REMOVE_FILTER_OPTION = 'REMOVE_FILTER_OPTION',
  SET_SEARCH_QUERY = 'SET_SEARCH_QUERY',
}
