/* eslint-disable no-shadow */

export enum MoviesActionTypes {
  // FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST',
  // FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS',
  // FETCH_MOVIES_FAIL = 'FETCH_MOVIES_FAIL',
  GET_MOVIES_BY_QUERY = 'GET_MOVIES_BY_QUERY',
  ADD_FILTER_OPTION = 'ADD_FILTER_OPTION',
  REMOVE_FILTER_OPTION = 'REMOVE_FILTER_OPTION',
  SET_SEARCH_QUERY = 'SET_SEARCH_QUERY',
  SET_SEARCH_PARAM = 'SET_SEARCH_PARAM',
  SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
  SET_MOVIES_PER_PAGE = 'SET_MOVIES_PER_PAGE',
  CLEAR_MOVIES_STATE = 'CLEAR_MOVIES_STATE',
}
