/* eslint-disable no-shadow */

export enum MoviesMutationTypes {
  SET_MOVIES = 'SET_MOVIES',
  SET_FILTERS = 'SET_FILTERS',
  SET_SEARCH_QUERY = 'SET_SEARCH_QUERY',
  SET_SEARCH_PARAM = 'SET_SEARCH_PARAM',
  SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
  SET_MOVIES_PER_PAGE = 'SET_MOVIES_PER_PAGE',
  SET_INITIAL_STATE = 'SET_INITIAL_STATE',
}
